{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "airflow.selectorLabels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "airflow.selectorLabels" . | nindent 8 }}
        component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        command: ["redis-server", "--requirepass", "{{ .Values.redis.password }}"]
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
    component: redis
{{- end }}
