{{- if and .Values.workers.enabled (eq .Values.airflow.executor "CeleryExecutor") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: worker
spec:
  serviceName: {{ include "airflow.fullname" . }}-worker
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      {{- include "airflow.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "airflow.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["airflow", "celery", "worker"]
        env:
        - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
          value: {{ .Values.workers.concurrency | quote }}
        {{- if .Values.airflow.useConfigMapForEnv }}
        envFrom:
        - configMapRef:
            name: {{ include "airflow.fullname" . }}-config
        {{- end }}
        volumeMounts:
        {{- include "airflow.dagsVolumeMount" . | nindent 8 }}
        {{- include "airflow.logsVolumeMount" . | nindent 8 }}
        {{- if .Values.airflow.externalAirflowCfg.enabled }}
        {{- include "airflow.externalAirflowCfgVolumeMount" . | nindent 8 }}
        {{- end }}
        {{- include "airflow.nasScriptsVolumeMount" . | nindent 8 }}
        resources:
          {{- toYaml .Values.workers.resources | nindent 10 }}
        {{- if .Values.workers.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - celery -A airflow.executors.celery_executor inspect ping -d celery@$HOSTNAME || exit 1
          initialDelaySeconds: {{ .Values.workers.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.workers.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.workers.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.workers.livenessProbe.failureThreshold }}
        {{- end }}
      {{- include "airflow.gitSyncContainer" . | nindent 6 }}
      volumes:
      {{- if .Values.dags.gitSync.enabled }}
      - name: dags
        emptyDir: {}
      {{- else }}
      {{- include "airflow.dagsVolume" . | nindent 6 }}
      {{- end }}
      {{- include "airflow.logsVolume" . | nindent 6 }}
      {{- include "airflow.gitSyncVolume" . | nindent 6 }}
      {{- if .Values.airflow.externalAirflowCfg.enabled }}
      {{- include "airflow.externalAirflowCfgVolume" . | nindent 6 }}
      {{- end }}
      {{- include "airflow.nasScriptsVolume" . | nindent 6 }}
{{- end }}
